### ISSUE TITLE
Moved: Badlands Reagent Run

### ISSUE THREAD

**Issue by WoWFeenix** [WoWFeenix/Alpenglow-Realm#1]
**When it occured**

**Description**
Got the quest, got the items needed for the quest, says its (completed) in quest log. But when I try to turn it in, I can't. Its like the quest giver thinks the quest isn't completed.

**How it works**

**How it should work**

**Link to WoWHead/WoWWiki**

**Comment by Snowie493** [comment]
This is working. invalid report. just abandon and retake.
