### ISSUE TITLE
Scholomance - Jandice Barov - Doesn't drop [Blood of Innocence]

### ISSUE THREAD

**Issue by Ownaron** [WoWFeenix/Alpenglow-Realm#12]
11/25/2018

Jandice Barov doesn't drop the [Blood of Innocence]
Jandice Barov SHOULD drop the [Blood of Innocence]
https://vanilla-twinhead.twinstar.cz/?npc=10503

**Comment by Snowie493** [comment]
Did you complete Quest http://classicdb.ch/?quest=5384 first? You need to finish the questline before it is guaranteed drop on every kill.

**Comment by WoWFeenix** [comment]
![image](https://user-images.githubusercontent.com/39406546/50091406-9c331500-020b-11e9-93ca-dbfa8450eb5e.png)
Invalid. You've to complete Kirtonos the Herald quest before you can drop Blood of Innocence.
