### ISSUE TITLE
Sentry totem bug

### ISSUE THREAD

**Issue by zhenyerdev** [WoWFeenix/Alpenglow-Realm#9]
**When it occured**
Today

**Description**
If you place Sentry totem and run away from it the Sentry totem buff would fade from your character. once you run back to Sentry totem location you would automatically gain control of it, but since you dont have Sentry totem buff you cant regain control of your character again. And you have to wait till sentry totem dissapear.

**How it works**
Described above
**How it should work**
Described above
**Link to WoWHead/WoWWiki**
https://classic.wowhead.com/spell=6495/sentry-totem#summons

**Comment by WoWFeenix** [comment]
We can't reproduce this bug, seems to be invalid.
